package com.example.satelliteprojectcompose.util


object TestTags {

    const val SATELLITE_SEARCH_BAR_COMPONENT = "SATELLITE_SEARCH_BAR_COMPONENT"
    const val SATELLITE_LIST_PROGRESS = "SATELLITE_LIST_PROGRESS"
    const val SATELLITE_DETAIL_PROGRESS = "SATELLITE_DETAIL_PROGRESS"
    const val SATELLITE_LAZY_COLUMN = "SATELLITE_LAZY_COLUMN"
    const val SATELLITE_DETAIL_ERROR = "SATELLITE_DETAIL_ERROR"
    const val SATELLITE_LIST_ERROR = "SATELLITE_LIST_ERROR"

}